<?php
$statusLabels = ['submitted' => 'Menunggu Approval Laboran', 'laboran_approved' => 'Menunggu Approval Kepala Lab', 'approved' => 'Disetujui', 'rejected' => 'Ditolak'];
$statusColors = ['submitted' => 'warning', 'laboran_approved' => 'info', 'approved' => 'success', 'rejected' => 'danger'];
$fmt = static fn (string $value): string => date('d M Y H:i', strtotime($value));
?>
<div class="page__section flex flex-col gap-4">
  <div class="card">
    <div class="card__header">
      <div>
        <span class="card__title">Persetujuan Peminjaman Asset</span>
        <div class="text-xs text-muted-foreground"><?= $tab === 'history' ? 'Riwayat Approval' : 'Menunggu Approval' ?></div>
      </div>
      <div class="card__action"><a href="<?= base_url('peminjaman/asset-loans') ?>" class="button button--outline button--neutral button--sm">Daftar Pengajuan</a></div>
    </div>
    <div class="card__body" style="border-bottom:1px solid var(--color-border);">
      <div class="toggle-group" data-stisla-toggle-group role="radiogroup" aria-label="Jenis data approval" style="display:inline-flex;width:max-content;max-width:100%;overflow-x:auto;">
        <a href="<?= base_url('peminjaman/asset-loans-approval?tab=pending') ?>" class="toggle" role="radio" aria-checked="<?= $tab === 'pending' ? 'true' : 'false' ?>" data-state="<?= $tab === 'pending' ? 'active' : 'inactive' ?>">Pengajuan Butuh Approval</a>
        <a href="<?= base_url('peminjaman/asset-loans-approval?tab=history') ?>" class="toggle" role="radio" aria-checked="<?= $tab === 'history' ? 'true' : 'false' ?>" data-state="<?= $tab === 'history' ? 'active' : 'inactive' ?>">History Approval</a>
      </div>
    </div>
    <div class="card__body" style="border-bottom:1px solid var(--color-border);">
      <form method="get" action="<?= base_url('peminjaman/asset-loans-approval') ?>" style="display:flex;flex-wrap:wrap;align-items:flex-end;gap:.75rem;">
        <input type="hidden" name="tab" value="<?= esc($tab) ?>">
        <div style="flex:1 1 280px;min-width:220px;"><label class="text-xs text-muted-foreground" for="q">Cari pengajuan</label><input type="search" class="input" id="q" name="q" value="<?= esc($search) ?>" placeholder="Nomor identitas, nama, kegiatan, atau asset..."></div>
        <div style="flex:0 1 220px;min-width:180px;"><label class="text-xs text-muted-foreground" for="status">Status Approval</label><select class="select" id="status" name="status"><option value="">Semua Status</option><?php foreach ($statusOptions as $option): ?><option value="<?= esc($option) ?>" <?= $status === $option ? 'selected' : '' ?>><?= esc($statusLabels[$option]) ?></option><?php endforeach; ?></select></div>
        <div style="flex:0 1 220px;min-width:180px;"><label class="text-xs text-muted-foreground" for="laboratory_uuid">Laboratorium</label><select class="select" id="laboratory_uuid" name="laboratory_uuid"><option value="">Semua Laboratorium</option><?php foreach ($laboratoryOptions as $lab): ?><option value="<?= esc($lab['uuid']) ?>" <?= $laboratoryUuid === $lab['uuid'] ? 'selected' : '' ?>><?= esc($lab['name']) ?></option><?php endforeach; ?></select></div>
        <div style="flex:0 0 120px;"><label class="text-xs text-muted-foreground" for="perPage">Per halaman</label><select class="select" id="perPage" name="perPage"><?php foreach ($perPageOptions as $option): ?><option value="<?= $option ?>" <?= $perPage === $option ? 'selected' : '' ?>><?= $option ?></option><?php endforeach; ?></select></div>
        <div style="display:flex;gap:.5rem;"><button type="submit" class="button button--primary button--sm">Filter</button><?php if ($search !== '' || $status !== '' || $laboratoryUuid !== ''): ?><a href="<?= base_url('peminjaman/asset-loans-approval?tab=' . $tab) ?>" class="button button--outline button--sm">Reset</a><?php endif; ?></div>
      </form>
    </div>
    <div class="card__body p-0">
      <?php if ($tab === 'history'): ?>
      <div class="table-responsive"><table class="table"><thead><tr><th>Waktu</th><th>Pemohon</th><th>Kegiatan</th><th>Keputusan</th><th>Oleh</th><th>Keterangan</th><th class="text-end">Aksi</th></tr></thead><tbody>
        <?php if (! empty($history)): foreach ($history as $entry): ?><tr><td><?= esc($fmt($entry['created_at'])) ?></td><td><strong><?= esc($entry['full_name']) ?></strong><div class="text-xs text-muted-foreground"><?= esc($entry['identity_number']) ?></div></td><td><?= esc($entry['event_name']) ?></td><td><span class="badge badge--soft badge--<?= $statusColors[$entry['to_status']] ?? 'secondary' ?>"><?= esc($statusLabels[$entry['to_status']] ?? $entry['to_status']) ?></span></td><td><?= esc($entry['changed_by_name'] ?: '-') ?></td><td><?= esc($entry['note'] ?: '-') ?></td><td class="text-end"><a href="<?= base_url('peminjaman/asset-loans/detail/' . $entry['proposal_uuid']) ?>" class="button button--info button--icon-only button--sm" title="Detail Pengajuan" aria-label="Detail Pengajuan"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4.5a7.5 7.5 0 1 0 0 15a7.5 7.5 0 0 0 0-15Zm0 3.25v.5m0 2.5v4.5" /></svg></a></td></tr><?php endforeach; else: ?><tr><td colspan="7" class="text-center text-muted-foreground py-8"><?= view('partials/empty_table_state', ['message' => 'Belum ada history approval.']) ?></td></tr><?php endif; ?>
      </tbody></table></div>
      <?php else: ?>
      <div class="table-responsive"><table class="table"><thead><tr><th>Pemohon</th><th>Kegiatan</th><th>Asset</th><th>Waktu Kegiatan</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
        <?php if (! empty($proposals)): foreach ($proposals as $proposal): ?><tr><td><strong><?= esc($proposal['full_name']) ?></strong><div class="text-xs text-muted-foreground"><?= esc($proposal['identity_number']) ?></div></td><td><strong><?= esc($proposal['event_name']) ?></strong></td><td><?= esc($proposal['asset_names']) ?></td><td><?= esc($fmt($proposal['event_start'])) ?><div class="text-xs text-muted-foreground">s.d. <?= esc($fmt($proposal['event_end'])) ?></div></td><td><span class="badge badge--soft badge--warning"><?= esc($statusLabels[$proposal['status']]) ?></span></td><td class="text-end"><div class="flex justify-end gap-1"><a href="<?= base_url('peminjaman/asset-loans/detail-approval/' . $proposal['uuid']) ?>" class="button button--info button--icon-only button--sm" title="Detail Pengajuan" aria-label="Detail Pengajuan"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M12 4.5a7.5 7.5 0 1 0 0 15a7.5 7.5 0 0 0 0-15Zm0 3.25v.5m0 2.5v4.5" /></svg></a><button type="button" class="button button--success button--icon-only button--sm" title="Setujui" aria-label="Setujui" onclick="openAssetApprovalDialog('approveConfirm', '<?= esc(base_url('peminjaman/asset-loans-approval/' . $proposal['uuid'] . '/approve'), 'js') ?>', '<?= esc($proposal['event_name'], 'js') ?>')"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="m5 12 4 4L19 6" /></svg></button><button type="button" class="button button--danger button--icon-only button--sm" title="Tolak" aria-label="Tolak" onclick="openAssetApprovalDialog('rejectConfirm', '<?= esc(base_url('peminjaman/asset-loans-approval/' . $proposal['uuid'] . '/reject'), 'js') ?>', '<?= esc($proposal['event_name'], 'js') ?>')"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="m7 7 10 10M17 7 7 17" /></svg></button></div></td></tr><?php endforeach; else: ?><tr><td colspan="6" class="text-center text-muted-foreground py-8"><?= view('partials/empty_table_state', ['message' => 'Tidak ada pengajuan yang menunggu approval.']) ?></td></tr><?php endif; ?>
      </tbody></table></div>
      <?php endif; ?>
    </div>
    <?php if ($pager->getTotal() > 0): ?><div class="card__body" style="border-top:1px solid var(--color-border);display:flex;flex-wrap:wrap;align-items:center;justify-content:space-between;gap:.75rem;"><span class="text-xs text-muted-foreground">Total <?= $pager->getTotal() ?> <?= $tab === 'history' ? 'history approval' : 'pengajuan' ?></span><?= $pager->only(['tab', 'q', 'status', 'perPage'])->links('default', 'app') ?></div><?php endif; ?>
  </div>
</div>

<div class="dialog dialog--sm" id="approveConfirm" data-stisla-dialog data-state="closed" role="alertdialog" aria-modal="true" aria-labelledby="approveConfirmLabel" aria-hidden="true" tabindex="-1"><div class="dialog__backdrop" data-stisla-dialog-dismiss></div><div class="dialog__panel"><div class="dialog__content"><button type="button" class="dialog__close" data-stisla-dialog-dismiss aria-label="Tutup">&times;</button><div class="dialog__body text-center pt-6"><h3 class="dialog__title mb-1" id="approveConfirmLabel">Setujui pengajuan ini?</h3><p class="text-muted-foreground">Pengajuan <strong data-slot="approve-event"></strong> akan disetujui.</p></div><form id="approveForm" method="post"><?= csrf_field() ?><div class="dialog__footer justify-center"><button type="button" class="button button--outline button--neutral" data-stisla-dialog-dismiss>Batal</button><button type="submit" class="button button--success">Ya, Setujui</button></div></form></div></div></div>
<div class="dialog dialog--sm" id="rejectConfirm" data-stisla-dialog data-state="closed" role="dialog" aria-modal="true" aria-labelledby="rejectConfirmLabel" aria-hidden="true" tabindex="-1"><div class="dialog__backdrop" data-stisla-dialog-dismiss></div><div class="dialog__panel"><div class="dialog__content"><div class="dialog__header"><h3 class="dialog__title" id="rejectConfirmLabel">Tolak Pengajuan</h3><button type="button" class="dialog__close" data-stisla-dialog-dismiss aria-label="Tutup">&times;</button></div><form id="rejectForm" method="post"><?= csrf_field() ?><div class="dialog__body"><p class="text-muted-foreground text-sm mb-4">Alasan penolakan akan terlihat oleh pemohon.</p><div class="field"><label class="field__label" for="reject_note">Alasan Penolakan <span class="text-danger">*</span></label><textarea class="input" id="reject_note" name="note" rows="3" required></textarea></div></div><div class="dialog__footer"><button type="button" class="button button--outline button--neutral" data-stisla-dialog-dismiss>Batal</button><button type="submit" class="button button--danger">Tolak Pengajuan</button></div></form></div></div></div>
<script>
function openAssetApprovalDialog(dialogId, actionUrl, eventName) { var dialog = document.getElementById(dialogId); var form = dialog.querySelector('form'); form.action = actionUrl; var slot = dialog.querySelector('[data-slot]'); if (slot) slot.textContent = eventName; if (dialogId === 'rejectConfirm') dialog.querySelector('#reject_note').value = ''; dialog.dataset.state = 'open'; dialog.setAttribute('aria-hidden', 'false'); }
document.addEventListener('click', function (event) { var dismiss = event.target.closest('[data-stisla-dialog-dismiss]'); if (! dismiss) return; var dialog = dismiss.closest('[data-stisla-dialog]'); if (dialog) { dialog.dataset.state = 'closed'; dialog.setAttribute('aria-hidden', 'true'); } });
document.querySelectorAll('#approveForm, #rejectForm').forEach(function (form) { form.addEventListener('submit', function () { var button = form.querySelector('button[type="submit"]'); if (button) button.disabled = true; }); });
</script>