<?php
$isEdit = ! empty($proposal);
$value = static fn (string $key, string $fallback = '') => old($key, $proposal[$key] ?? $fallback);
$datetime = static fn (string $key) => old($key, ! empty($proposal[$key]) ? date('Y-m-d\TH:i', strtotime($proposal[$key])) : '');
$minDateTime = date('Y-m-d\TH:i');
?>
<div class="page__section"><div class="card"><div class="card__header"><span class="card__title"><?= $isEdit ? 'Edit' : 'Ajukan' ?> Pengajuan Peminjaman Asset</span></div><div class="card__body">
<form action="<?= base_url('peminjaman/asset-loans/' . ($isEdit ? 'update/' . $proposal['uuid'] : 'store')) ?>" method="post" class="flex flex-col gap-6">
<?= csrf_field() ?><fieldset style="border:1px solid var(--color-border);border-radius:.75rem;padding:1.25rem;margin:0"><legend class="text-sm font-semibold">Data Pemohon</legend><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div class="field"><label class="field__label" for="identity_number">Nomor Identitas *</label><input class="input w-full" id="identity_number" name="identity_number" value="<?= esc($value('identity_number', $user->identity_number ?? '')) ?>" required readonly></div><div class="field"><label class="field__label" for="full_name">Nama Lengkap *</label><input class="input w-full" id="full_name" name="full_name" value="<?= esc($value('full_name', $user->username ?? '')) ?>" required readonly></div><div class="field"><label class="field__label" for="phone">Nomor HP *</label><input class="input w-full" id="phone" name="phone" value="<?= esc($value('phone', $user->phone ?? '')) ?>" required readonly></div><div class="field"><label class="field__label" for="email">Email *</label><input type="email" class="input w-full" id="email" name="email" value="<?= esc($value('email', $user->email ?? '')) ?>" required readonly></div><div class="field"><label class="field__label" for="proposal_date">Tanggal Pengajuan *</label><input type="date" class="input w-full" id="proposal_date" name="proposal_date" value="<?= esc($value('proposal_date', date('Y-m-d'))) ?>" readonly required></div></div></fieldset>
<fieldset style="border:1px solid var(--color-border);border-radius:.75rem;padding:1.25rem;margin:0"><legend class="text-sm font-semibold">Detail Kegiatan</legend><div class="flex flex-col gap-4"><div class="field"><label class="field__label" for="event_name">Nama Kegiatan *</label><input class="input w-full" id="event_name" name="event_name" value="<?= esc($value('event_name')) ?>" required></div><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div class="field"><label class="field__label" for="event_start">Waktu Mulai *</label><input type="datetime-local" class="input w-full" id="event_start" name="event_start" value="<?= esc($datetime('event_start')) ?>" min="<?= esc($minDateTime) ?>" required></div><div class="field"><label class="field__label" for="event_end">Waktu Selesai *</label><input type="datetime-local" class="input w-full" id="event_end" name="event_end" value="<?= esc($datetime('event_end')) ?>" min="<?= esc($minDateTime) ?>" required></div></div><div class="field"><span class="field__label">Asset akan digunakan di *</span><div class="flex flex-col gap-2"><label class="flex gap-2 items-center"><input type="radio" name="usage_location" value="inside_lab" <?= $value('usage_location') === 'inside_lab' ? 'checked' : '' ?> required> Di dalam laboratorium</label><label class="flex gap-2 items-center"><input type="radio" name="usage_location" value="outside_lab" <?= $value('usage_location') === 'outside_lab' ? 'checked' : '' ?>> Di luar laboratorium</label></div></div></div></fieldset>
<fieldset style="border:1px solid var(--color-border);border-radius:.75rem;padding:1.25rem;margin:0"><legend class="text-sm font-semibold">Persetujuan</legend><label class="flex gap-2 items-start text-sm"><input type="checkbox" class="checkbox" name="acknowledgement" value="1" <?= old('acknowledgement', $proposal['acknowledgement'] ?? '') === '1' || (int) ($proposal['acknowledgement'] ?? 0) === 1 ? 'checked' : '' ?> required><span>Saya memahami bahwa jadwal asset dapat dibatalkan atau ditunda apabila ada kebutuhan institusi.</span></label></fieldset>
<div class="flex justify-end gap-2"><a href="<?= base_url('peminjaman/asset-loans') ?>" class="button button--outline button--neutral">Batal</a><button class="button button--primary">Simpan Pengajuan</button></div>
</form></div></div></div>
