<?php
/** @var array $rows */
/** @var string $q */
/** @var string $start_date */
/** @var string $end_date */
/** @var string $status */
$fmt = static fn ($value): string => 'Rp ' . number_format((float) $value, 0, ',', '.');
?>
<div class="page__section"><div class="card"><div class="card__header"><div><span class="card__title">Laporan BHP per Program Studi</span><div class="text-xs text-muted-foreground">Agregasi seluruh laboratorium yang berada di bawah program studi</div></div><div class="card__action"><a class="button button--outline button--sm" href="<?= base_url('bhp-report/export/csv?' . http_build_query(['q' => $q, 'start_date' => $start_date, 'end_date' => $end_date, 'status' => $status])) ?>">Export CSV</a></div></div><div class="card__body">
<form method="get" action="<?= base_url('bhp-report') ?>" style="display:flex;flex-wrap:nowrap;align-items:end;gap:.5rem;overflow-x:auto;padding-bottom:.25rem"><input class="input" style="min-width:18rem" name="q" value="<?= esc($q) ?>" placeholder="Cari kode atau program studi"><input class="input" type="date" name="start_date" value="<?= esc($start_date) ?>"><input class="input" type="date" name="end_date" value="<?= esc($end_date) ?>"><select class="input" style="min-width:12rem" name="status"><option value="">Semua status non-draft</option><?php foreach (['PENDING_REVIEW', 'NEED_REVISION', 'APPROVED_BY_KALAB', 'FUND_DISBURSED', 'EVIDEN_SUBMITTED', 'COMPLETED'] as $option): ?><option value="<?= $option ?>" <?= $status === $option ? 'selected' : '' ?>><?= esc($option) ?></option><?php endforeach; ?></select><button class="button button--outline">Filter</button></form>
<div class="table-responsive" style="margin-top:1rem"><table class="table"><thead><tr><th>Kode Prodi</th><th>Program Studi</th><th>Laboratorium</th><th>Jumlah Pengajuan</th><th>Total Estimasi</th><th>Total Realisasi</th><th>Selisih</th></tr></thead><tbody><?php if (empty($rows)): ?><tr><td colspan="7"><?= view('partials/empty_table_state', ['message' => 'Belum ada data laporan.']) ?></td></tr><?php endif; ?><?php foreach ($rows as $row): $variance = (float) $row['total_realisasi'] - (float) $row['total_estimasi']; ?><tr><td><?= esc($row['program_code'] ?? '-') ?></td><td><strong><?= esc($row['program_name'] ?? 'Tanpa Program Studi') ?></strong></td><td><?= esc($row['laboratories'] ?? '-') ?></td><td><?= esc($row['total_pengajuan']) ?></td><td><?= $fmt($row['total_estimasi']) ?></td><td><?= $fmt($row['total_realisasi']) ?></td><td class="<?= $variance > 0 ? 'text-danger' : '' ?>"><?= $fmt($variance) ?></td></tr><?php endforeach; ?></tbody></table></div>
</div></div></div>
